# copied from .travis.yml
name: Run tests

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ytdl_test_set.may_fail || matrix.python.may_fail }}
    strategy:
      matrix:
        python: [
          { name: '2.7', may_fail: true, major: 2, jython: false },
          { name: '3.8', may_fail: false, major: 3, jython: false },
          { name: '3.7', may_fail: false, major: 3, jython: false },
          { name: '3.6', may_fail: false, major: 3, jython: false },
          { name: '3.5', may_fail: false, major: 3, jython: false },
          { name: 'pypy3', may_fail: false, major: 3, jython: false },
          { name: 'pypy2', may_fail: true, major: 2, jython: false },
          { name: 'jython', may_fail: true, major: 2, jython: true }
        ]
        ytdl_test_set: [
          { name: 'download', may_fail: true },
          { name: 'core', may_fail: false }
        ]
    env:
      YTDL_TEST_SET: ${{ matrix.ytdl_test_set.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python.name }}
        uses: actions/setup-python@v2
        if: ${{ !matrix.python.jython }}
        with:
          python-version: ${{ matrix.python.name }}
      - name: Install Jython
        if: ${{ matrix.python.jython }}
        run: |
          ./devscripts/install_jython.sh
          echo "$HOME/jython/bin" >> $GITHUB_PATH
          ln -s "$HOME/jython/bin/jython" "$HOME/jython/bin/python"
      - name: Install deps (Python 3)
        if: ${{ matrix.python.major == 3 && !matrix.python.jython }}
        run: pip3 install nose
      - name: Install deps (Python 2)
        if: ${{ matrix.python.major == 2 && !matrix.python.jython }}
        run: pip install nose
      - name: Run test
        continue-on-error: ${{ matrix.ytdl_test_set.may_fail || matrix.python.may_fail }}
        run: ./devscripts/run_tests.sh
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: pip3 install flake8
      - name: Run flake8 .
        run: flake8 .
